#!/bin/sh

. $(dirname $0)/functions.sh

OUTFILE="/etc/build-args"

platform=$(determine_platform)
export platform

echo "tag: ${tag}"
echo "version: ${version}"
echo "input: ${input}"
echo "image: ${image}"
echo "supplementary: ${supplementary}"
echo "platform: ${platform}"


touch ${OUTFILE}
chmod 644 ${OUTFILE}
:> ${OUTFILE}

echo "tag: ${tag}" >> ${OUTFILE}
echo "version: ${version}" >> ${OUTFILE}
echo "input: ${input}" >> ${OUTFILE}
echo "image: ${image}" >> ${OUTFILE}
echo "supplementary: ${supplementary}" >> ${OUTFILE}
echo "platform: ${platform}" >> ${OUTFILE}

echo "----Branch----" >> ${OUTFILE}
calculate_tags >> ${OUTFILE}
echo "----Override----" >> ${OUTFILE}
OVERRIDE_BRANCH="main"
export OVERRIDE_BRANCH
calculate_tags >> ${OUTFILE}

